services:
  db:
    build: db
    image: gtardif/sentences-db

  words:
    build: words
    image: gtardif/sentences-api

  web:
    build: web
    image: gtardif/sentences-web
    ports:
      - "80:80"
    secrets:
      - source: mysecret1
        target: mytarget1
      - mysecret2

secrets:
  mysecret1:
    file: ./my_secret1.txt
  mysecret2:
    file: ./my_secret2.txt
