services:
  db:
    build: aci-demo/db
    image: gtardif/sentences-db

  service1:
    container_name: words
    build: aci-demo/words
    image: gtardif/sentences-api
    ports:
      - "8080:8080"
  web:
    build: aci-demo/web
    image: gtardif/sentences-web
    ports:
      - "80:80"
